-- MySQL Script generated by MySQL Workbench
-- Sat Dec 18 19:08:21 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema railway_station
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema railway_station
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `railway_station` DEFAULT CHARACTER SET utf8 ;
USE `railway_station` ;

-- -----------------------------------------------------
-- Table `railway_station`.`access_rights`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `railway_station`.`access_rights` (
  `access_right_id` INT NOT NULL AUTO_INCREMENT,
  `access_right_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`access_right_id`),
  UNIQUE INDEX `access_right_name_UNIQUE` (`access_right_name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `railway_station`.`workers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `railway_station`.`workers` (
  `worker_id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `phone_number` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL DEFAULT '0000',
  `access_right_id` INT NOT NULL,
  PRIMARY KEY (`worker_id`),
  INDEX `fk_workers_access_rights1_idx` (`access_right_id` ASC) VISIBLE,
  CONSTRAINT `fk_workers_access_rights1`
    FOREIGN KEY (`access_right_id`)
    REFERENCES `railway_station`.`access_rights` (`access_right_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `railway_station`.`clients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `railway_station`.`clients` (
  `client_id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `pass_number` VARCHAR(45) NOT NULL,
  `phone_number` VARCHAR(45) NULL,
  PRIMARY KEY (`client_id`),
  UNIQUE INDEX `pass_number_UNIQUE` (`pass_number` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `railway_station`.`vans`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `railway_station`.`vans` (
  `van_id` INT NOT NULL AUTO_INCREMENT,
  `van_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`van_id`),
  UNIQUE INDEX `van_name_UNIQUE` (`van_name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `railway_station`.`sit_places`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `railway_station`.`sit_places` (
  `sit_place_id` INT NOT NULL AUTO_INCREMENT,
  `place_name` VARCHAR(45) NOT NULL,
  `place_price` INT UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (`sit_place_id`),
  UNIQUE INDEX `place_name_UNIQUE` (`place_name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `railway_station`.`trains`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `railway_station`.`trains` (
  `train_id` INT NOT NULL AUTO_INCREMENT,
  `train_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`train_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `railway_station`.`trains_has_vans_has_sits`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `railway_station`.`trains_has_vans_has_sits` (
  `train_van_sit_id` INT NOT NULL AUTO_INCREMENT,
  `train_id` INT NOT NULL,
  `van_id` INT NOT NULL,
  `sit_place_id` INT NOT NULL,
  INDEX `fk_vans_has_trains_vans1_idx` (`van_id` ASC) VISIBLE,
  INDEX `fk_vans_has_trains_sit_places1_idx` (`sit_place_id` ASC) VISIBLE,
  INDEX `fk_vans_has_sits_trains1_idx` (`train_id` ASC) VISIBLE,
  PRIMARY KEY (`train_van_sit_id`),
  CONSTRAINT `fk_vans_has_trains_vans1`
    FOREIGN KEY (`van_id`)
    REFERENCES `railway_station`.`vans` (`van_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_vans_has_trains_sit_places1`
    FOREIGN KEY (`sit_place_id`)
    REFERENCES `railway_station`.`sit_places` (`sit_place_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_vans_has_sits_trains1`
    FOREIGN KEY (`train_id`)
    REFERENCES `railway_station`.`trains` (`train_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `railway_station`.`tickets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `railway_station`.`tickets` (
  `ticket_id` INT NOT NULL AUTO_INCREMENT,
  `client_id` INT NOT NULL,
  `worker_id` INT NOT NULL,
  `all_price` INT UNSIGNED NOT NULL DEFAULT 0,
  `train_van_sit_id` INT NOT NULL,
  PRIMARY KEY (`ticket_id`),
  INDEX `fk_tikets_clients1_idx` (`client_id` ASC) VISIBLE,
  INDEX `fk_tikets_workers1_idx` (`worker_id` ASC) VISIBLE,
  INDEX `fk_tickets_trains_has_vans_has_sits1_idx` (`train_van_sit_id` ASC) VISIBLE,
  CONSTRAINT `fk_tikets_clients1`
    FOREIGN KEY (`client_id`)
    REFERENCES `railway_station`.`clients` (`client_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tikets_workers1`
    FOREIGN KEY (`worker_id`)
    REFERENCES `railway_station`.`workers` (`worker_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tickets_trains_has_vans_has_sits1`
    FOREIGN KEY (`train_van_sit_id`)
    REFERENCES `railway_station`.`trains_has_vans_has_sits` (`train_van_sit_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `railway_station`.`destinations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `railway_station`.`destinations` (
  `destination_id` INT NOT NULL AUTO_INCREMENT,
  `destination_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`destination_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `railway_station`.`trains_destinations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `railway_station`.`trains_destinations` (
  `train_destination_id` INT NOT NULL AUTO_INCREMENT,
  `train_id` INT NOT NULL,
  `destination_id` INT NOT NULL,
  `departure_time` DATETIME NULL,
  `arrival_time` DATETIME NULL,
  PRIMARY KEY (`train_destination_id`),
  INDEX `fk_trains_has_destinations_destinations1_idx` (`destination_id` ASC) VISIBLE,
  INDEX `fk_trains_has_destinations_trains1_idx` (`train_id` ASC) VISIBLE,
  CONSTRAINT `fk_trains_has_destinations_trains1`
    FOREIGN KEY (`train_id`)
    REFERENCES `railway_station`.`trains` (`train_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_trains_has_destinations_destinations1`
    FOREIGN KEY (`destination_id`)
    REFERENCES `railway_station`.`destinations` (`destination_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `railway_station`;

DELIMITER $$
USE `railway_station`$$
CREATE DEFINER = CURRENT_USER TRIGGER `railway_station`.`trains_BEFORE_DELETE` BEFORE DELETE ON `trains` FOR EACH ROW
BEGIN
	SET @trainid = OLD.train_id;
    DELETE FROM trains_has_vans_has_sits WHERE trains_has_vans_has_sits.train_id like @trainid;   
    DELETE FROM trains_destinations WHERE trains_destinations.train_id like @trainid;   
END$$

USE `railway_station`$$
CREATE DEFINER = CURRENT_USER TRIGGER `railway_station`.`trains_has_vans_has_sits_BEFORE_DELETE` BEFORE DELETE ON `trains_has_vans_has_sits` FOR EACH ROW
BEGIN
	SET @trainvansitid = OLD.train_van_sit_id;
    DELETE FROM tickets WHERE tickets.train_van_sit_id like @trainvansitid;   
END$$

USE `railway_station`$$
CREATE DEFINER = CURRENT_USER TRIGGER `railway_station`.`tickets_BEFORE_INSERT` BEFORE INSERT ON `tickets` FOR EACH ROW
BEGIN
	SET @sit_place = (SELECT sit_place_id FROM trains_has_vans_has_sits WHERE train_van_sit_id = NEW.train_van_sit_id);
	SET NEW.all_price = (SELECT place_price FROM sit_places WHERE sit_place_id = @sit_place);
END$$


DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
